services:
  frontend:
    image: my-image:latest
    container_name: frontend-container
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    command: ["nginx", "-g", "daemon off;"]