name: ci/cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: docker build . --file Dockerfile --tag my-image-name:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: run
      run: docker run --rm my-image-name:latest npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: deploy
      run: docker-compose up -d