name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check
        uses: actions/checkout@v4

      - name: build
        run: docker build . --file Dockerfile --tag my-image:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: check
        uses: actions/checkout@v4

      - name: run
        run: docker run --rm -v $(pwd)/task/frontend:/frontend my-image npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: check
        uses: actions/checkout@v4

      - name: deploy
        run: docker-compose up -d
