name: docker image ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run:
        docker build -t my-image:latest .
        docker save my-image:latest -o my-image.tar

    - name: list images
      run: docker images

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: my-image.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: download image
        uses: actions/download-artifact@v4
        with:
            name: docker-image
      - name: load image
        run: docker load -i my-image.tar
      - name: run
        run: docker run --rm my-image:latest npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - name: download doker
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: load image
        run: docker load -i my-image.tar
      - name: deploy
        run: docker-compose up -d