stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t my-image-name .

test-job:
  stage: test
  script:
    - docker run --rm my-image-name npm test

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d
