name: ci_cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag my-image:latest

      - name: Run tests
        run: docker run --rm my-image:latest npm test

      - name: Deploy with Docker Compose
        run: docker-compose up -d
