name: ci/cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: docker build . --file Dockerfile --tag my-image:$(date +%s)

      - name: run
        run: docker run --rm my-image npm test

      - name: deploy
        run: docker-compose up -d
